In [1]:
from PIL import Image

In [2]:
def convertir_a_grises(ruta_entrada, ruta_salida):
    """
    Convierte una imagen a escala de grises.
    
    :param ruta_entrada: Ruta de la imagen de entrada (color).
    :param ruta_salida: Ruta donde se guardará la imagen en escala de grises.
    """
    try:
        # Cargar la imagen
        imagen = Image.open(ruta_entrada)
        # Convertir a escala de grises
        imagen_grises = imagen.convert('L')
        # Guardar la imagen
        imagen_grises.save(ruta_salida)
        print(f"Imagen convertida a escala de grises y guardada en: {ruta_salida}")
    except Exception as e:
        print(f"Error al convertir a grises: {e}")

In [3]:
def convertir_a_color(ruta_entrada, ruta_salida):
    """
    Convierte una imagen en escala de grises a color (replicando tonos de gris en RGB).
    
    :param ruta_entrada: Ruta de la imagen de entrada (escala de grises).
    :param ruta_salida: Ruta donde se guardará la imagen en color.
    """
    try:
        # Cargar la imagen
        imagen = Image.open(ruta_entrada)
        # Convertir a color (RGB)
        imagen_color = imagen.convert('RGB')
        # Guardar la imagen
        imagen_color.save(ruta_salida)
        print(f"Imagen convertida a color y guardada en: {ruta_salida}")
    except Exception as e:
        print(f"Error al convertir a color: {e}")

In [4]:
# Ejemplo de uso
ruta_original = 'Foto.jpg'  # Cambia por la ruta de tu imagen
ruta_grises = 'imagen_grises.jpg'
ruta_color = 'imagen_color.jpg'

In [5]:
# Convertir a grises
convertir_a_grises(ruta_original, ruta_grises)

Imagen convertida a escala de grises y guardada en: imagen_grises.jpg


In [6]:
# Convertir de grises a color
convertir_a_color(ruta_grises, ruta_color)

Imagen convertida a color y guardada en: imagen_color.jpg


In [8]:
from PIL import Image

def obtener_valores_unicos_rgb(ruta_imagen):
    """
    Obtiene los valores únicos RGB de los píxeles de una imagen.
    
    :param ruta_imagen: Ruta de la imagen de entrada.
    :return: Un conjunto de tuplas con los valores RGB únicos.
    """
    try:
        # Cargar la imagen
        imagen = Image.open(ruta_imagen)
        
        # Convertir la imagen a RGB (en caso de que no lo sea)
        imagen_rgb = imagen.convert('RGB')
        
        # Obtener los píxeles de la imagen
        pixeles = imagen_rgb.getdata()
        
        # Usar un conjunto para obtener los valores únicos de los píxeles (sin duplicados)
        valores_unicos_rgb = set(pixeles)
        
        # Mostrar la cantidad de valores únicos encontrados
        print(f"Se encontraron {len(valores_unicos_rgb)} colores únicos en la imagen.")
        
        return valores_unicos_rgb
    
    except Exception as e:
        print(f"Error al obtener los valores únicos RGB: {e}")
        return set()

In [9]:
# Ejemplo de uso
ruta_imagen = 'Foto.jpg'  # Cambia por la ruta de tu imagen

valores_unicos = obtener_valores_unicos_rgb(ruta_imagen)
print(valores_unicos)  # Mostrar los valores únicos RGB

Se encontraron 4747 colores únicos en la imagen.
{(237, 201, 153), (215, 217, 216), (126, 127, 131), (251, 250, 255), (188, 203, 210), (150, 118, 69), (253, 255, 245), (243, 185, 111), (254, 244, 235), (255, 227, 176), (141, 169, 193), (215, 189, 154), (167, 193, 220), (216, 196, 161), (254, 255, 250), (253, 230, 188), (152, 191, 230), (191, 212, 231), (226, 190, 130), (179, 183, 186), (164, 197, 228), (246, 213, 170), (255, 251, 240), (214, 230, 246), (248, 211, 158), (231, 199, 150), (255, 223, 178), (234, 208, 173), (253, 223, 185), (244, 196, 124), (235, 189, 127), (121, 151, 179), (244, 227, 197), (242, 201, 147), (255, 252, 241), (253, 252, 248), (202, 202, 202), (239, 177, 94), (255, 244, 237), (234, 250, 255), (226, 193, 140), (239, 184, 102), (188, 212, 236), (223, 187, 135), (81, 95, 108), (156, 182, 207), (166, 164, 165), (246, 220, 187), (255, 226, 188), (139, 170, 198), (236, 183, 113), (247, 227, 194), (131, 131, 131), (223, 189, 144), (230, 230, 228), (185, 228, 255), (1

In [10]:
import numpy as np
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

def normalizar_colores(ruta_imagen, n_colores=4):
    """
    Normaliza los colores de una imagen a un número reducido de colores usando k-means clustering.
    
    :param ruta_imagen: Ruta de la imagen de entrada.
    :param n_colores: Número de colores que se desean obtener (por defecto 4).
    :return: Una nueva imagen con los colores normalizados.
    """
    try:
        # Cargar la imagen
        imagen = Image.open(ruta_imagen)
        
        # Convertir la imagen a RGB (en caso de que no lo sea)
        imagen_rgb = imagen.convert('RGB')
        
        # Obtener los datos de los píxeles
        pixeles = np.array(imagen_rgb).reshape(-1, 3)
        
        # Usar KMeans para agrupar los colores
        kmeans = KMeans(n_clusters=n_colores, random_state=42)
        kmeans.fit(pixeles)
        
        # Obtener los centroides (colores promedio) de los clusters
        colores_reducidos = kmeans.cluster_centers_.astype(int)
        
        # Asignar a cada píxel el color del centroide más cercano
        etiquetas = kmeans.predict(pixeles)
        pixeles_normalizados = colores_reducidos[etiquetas]
        
        # Crear una nueva imagen con los colores normalizados
        nueva_imagen = pixeles_normalizados.reshape(imagen_rgb.size[1], imagen_rgb.size[0], 3)
        imagen_normalizada = Image.fromarray(nueva_imagen.astype('uint8'))
        
        # Mostrar los colores representativos
        print(f"Colores normalizados: {colores_reducidos}")
        
        # Mostrar la imagen resultante
        imagen_normalizada.show()
        
        # Guardar la nueva imagen
        ruta_salida = 'imagen_normalizada.jpg'
        imagen_normalizada.save(ruta_salida)
        print(f"Imagen normalizada guardada en: {ruta_salida}")
        
        return imagen_normalizada
    
    except Exception as e:
        print(f"Error al normalizar los colores: {e}")
        return None


In [11]:
# Ejemplo de uso
ruta_imagen = 'Foto.jpg'  # Cambia por la ruta de tu imagen
imagen_normalizada = normalizar_colores(ruta_imagen, n_colores=4)

c:\Users\juanp\OneDrive\Documentos\Universidad\Vida\GA\env\Lib\site-packages\joblib\externals\loky\backend\context.py:136: UserWarning: Could not find the number of physical cores for the following reason:
found 0 physical cores < 1
Returning the number of logical cores instead. You can silence this warning by setting LOKY_MAX_CPU_COUNT to the number of cores you want to use.
  warnings.warn(
  File "c:\Users\juanp\OneDrive\Documentos\Universidad\Vida\GA\env\Lib\site-packages\joblib\externals\loky\backend\context.py", line 282, in _count_physical_cores
    raise ValueError(f"found {cpu_count_physical} physical cores < 1")


Colores normalizados: [[163 184 203]
 [117 116 116]
 [254 254 253]
 [237 197 142]]
Imagen normalizada guardada en: imagen_normalizada.jpg
